var tree = [["Eloquent",,"",
                [["Otis",,"",
                [["Configuration","Eloquent\/Otis\/Configuration.html","",
                [["Exception","Eloquent\/Otis\/Configuration\/Exception.html","",
                [["InvalidPasswordLengthException","Eloquent\/Otis\/Configuration\/Exception\/InvalidPasswordLengthException.html"," < Exception",
                [        ]]        ]],["AbstractOtpConfiguration","Eloquent\/Otis\/Configuration\/AbstractOtpConfiguration.html","",
                [        ]],["HashAlgorithm","Eloquent\/Otis\/Configuration\/HashAlgorithm.html"," < Enumeration",
                [        ]],["HotpConfiguration","Eloquent\/Otis\/Configuration\/HotpConfiguration.html"," < AbstractOtpConfiguration",
                [        ]],["HotpConfigurationInterface","Eloquent\/Otis\/Configuration\/HotpConfigurationInterface.html","",
                [        ]],["OtpConfigurationInterface","Eloquent\/Otis\/Configuration\/OtpConfigurationInterface.html","",
                [        ]],["TotpConfiguration","Eloquent\/Otis\/Configuration\/TotpConfiguration.html"," < AbstractOtpConfiguration",
                [        ]],["TotpConfigurationInterface","Eloquent\/Otis\/Configuration\/TotpConfigurationInterface.html","",
                [        ]]        ]],["Generator","Eloquent\/Otis\/Generator.html","",
                [["HotpGenerator","Eloquent\/Otis\/Generator\/HotpGenerator.html","",
                [        ]],["HotpGeneratorInterface","Eloquent\/Otis\/Generator\/HotpGeneratorInterface.html","",
                [        ]],["OtpValue","Eloquent\/Otis\/Generator\/OtpValue.html","",
                [        ]],["OtpValueInterface","Eloquent\/Otis\/Generator\/OtpValueInterface.html","",
                [        ]],["TotpGenerator","Eloquent\/Otis\/Generator\/TotpGenerator.html","",
                [        ]],["TotpGeneratorInterface","Eloquent\/Otis\/Generator\/TotpGeneratorInterface.html","",
                [        ]]        ]],["Uri",,"",
                [["GoogleAuthenticator","Eloquent\/Otis\/Uri\/GoogleAuthenticator.html","",
                [["GoogleAuthenticatorUriFactory","Eloquent\/Otis\/Uri\/GoogleAuthenticator\/GoogleAuthenticatorUriFactory.html","",
                [        ]],["GoogleAuthenticatorUriFactoryInterface","Eloquent\/Otis\/Uri\/GoogleAuthenticator\/GoogleAuthenticatorUriFactoryInterface.html","",
                [        ]]        ]],["QrCode","Eloquent\/Otis\/Uri\/QrCode.html","",
                [["ErrorCorrectionLevel","Eloquent\/Otis\/Uri\/QrCode\/ErrorCorrectionLevel.html"," < Multiton",
                [        ]],["GoogleChartsQrCodeUriFactory","Eloquent\/Otis\/Uri\/QrCode\/GoogleChartsQrCodeUriFactory.html","",
                [        ]],["KaywaQrCodeUriFactory","Eloquent\/Otis\/Uri\/QrCode\/KaywaQrCodeUriFactory.html","",
                [        ]],["QrCodeUriFactoryInterface","Eloquent\/Otis\/Uri\/QrCode\/QrCodeUriFactoryInterface.html","",
                [        ]],["QrServerQrCodeUriFactory","Eloquent\/Otis\/Uri\/QrCode\/QrServerQrCodeUriFactory.html","",
                [        ]]        ]]        ]],["Validator","Eloquent\/Otis\/Validator.html","",
                [["Exception","Eloquent\/Otis\/Validator\/Exception.html","",
                [["OtpParametersTypeMismatchException","Eloquent\/Otis\/Validator\/Exception\/OtpParametersTypeMismatchException.html"," < Exception",
                [        ]],["UnsupportedOtpConfigurationException","Eloquent\/Otis\/Validator\/Exception\/UnsupportedOtpConfigurationException.html"," < Exception",
                [        ]]        ]],["Parameters","Eloquent\/Otis\/Validator\/Parameters.html","",
                [["AbstractOtpParameters","Eloquent\/Otis\/Validator\/Parameters\/AbstractOtpParameters.html","",
                [        ]],["HotpParameters","Eloquent\/Otis\/Validator\/Parameters\/HotpParameters.html"," < AbstractOtpParameters",
                [        ]],["HotpParametersInterface","Eloquent\/Otis\/Validator\/Parameters\/HotpParametersInterface.html","",
                [        ]],["OtpParametersInterface","Eloquent\/Otis\/Validator\/Parameters\/OtpParametersInterface.html","",
                [        ]],["TotpParameters","Eloquent\/Otis\/Validator\/Parameters\/TotpParameters.html"," < AbstractOtpParameters",
                [        ]],["TotpParametersInterface","Eloquent\/Otis\/Validator\/Parameters\/TotpParametersInterface.html","",
                [        ]]        ]],["Result","Eloquent\/Otis\/Validator\/Result.html","",
                [["Exception","Eloquent\/Otis\/Validator\/Result\/Exception.html","",
                [["InvalidResultException","Eloquent\/Otis\/Validator\/Result\/Exception\/InvalidResultException.html"," < Exception",
                [        ]]        ]],["AbstractOtpValidationResult","Eloquent\/Otis\/Validator\/Result\/AbstractOtpValidationResult.html","",
                [        ]],["HotpValidationResult","Eloquent\/Otis\/Validator\/Result\/HotpValidationResult.html"," < AbstractOtpValidationResult",
                [        ]],["HotpValidationResultInterface","Eloquent\/Otis\/Validator\/Result\/HotpValidationResultInterface.html","",
                [        ]],["OtpValidationResultInterface","Eloquent\/Otis\/Validator\/Result\/OtpValidationResultInterface.html","",
                [        ]],["TotpValidationResult","Eloquent\/Otis\/Validator\/Result\/TotpValidationResult.html"," < AbstractOtpValidationResult",
                [        ]],["TotpValidationResultInterface","Eloquent\/Otis\/Validator\/Result\/TotpValidationResultInterface.html","",
                [        ]],["ValidationResultType","Eloquent\/Otis\/Validator\/Result\/ValidationResultType.html"," < Enumeration",
                [        ]]        ]],["HotpValidator","Eloquent\/Otis\/Validator\/HotpValidator.html","",
                [        ]],["HotpValidatorInterface","Eloquent\/Otis\/Validator\/HotpValidatorInterface.html","",
                [        ]],["OtpValidator","Eloquent\/Otis\/Validator\/OtpValidator.html","",
                [        ]],["OtpValidatorInterface","Eloquent\/Otis\/Validator\/OtpValidatorInterface.html","",
                [        ]],["TotpValidator","Eloquent\/Otis\/Validator\/TotpValidator.html","",
                [        ]],["TotpValidatorInterface","Eloquent\/Otis\/Validator\/TotpValidatorInterface.html","",
                [        ]]        ]]        ]]        ]]        ]

