var tree = [["Eloquent",,"",
                [["Otis",,"",
                [["Configuration","Eloquent\/Otis\/Configuration.html","",
                [["AbstractOtpConfiguration","Eloquent\/Otis\/Configuration\/AbstractOtpConfiguration.html","",
                [        ]],["HashAlgorithm","Eloquent\/Otis\/Configuration\/HashAlgorithm.html"," < Enumeration",
                [        ]],["HotpConfiguration","Eloquent\/Otis\/Configuration\/HotpConfiguration.html"," < AbstractOtpConfiguration",
                [        ]],["HotpConfigurationInterface","Eloquent\/Otis\/Configuration\/HotpConfigurationInterface.html","",
                [        ]],["OtpConfigurationInterface","Eloquent\/Otis\/Configuration\/OtpConfigurationInterface.html","",
                [        ]],["TotpConfiguration","Eloquent\/Otis\/Configuration\/TotpConfiguration.html"," < AbstractOtpConfiguration",
                [        ]],["TotpConfigurationInterface","Eloquent\/Otis\/Configuration\/TotpConfigurationInterface.html","",
                [        ]]        ]],["GoogleAuthenticator","Eloquent\/Otis\/GoogleAuthenticator.html","",
                [["GoogleAuthenticatorUriFactory","Eloquent\/Otis\/GoogleAuthenticator\/GoogleAuthenticatorUriFactory.html","",
                [        ]],["GoogleAuthenticatorUriFactoryInterface","Eloquent\/Otis\/GoogleAuthenticator\/GoogleAuthenticatorUriFactoryInterface.html","",
                [        ]]        ]],["Hotp","Eloquent\/Otis\/Hotp.html","",
                [["Exception","Eloquent\/Otis\/Hotp\/Exception.html","",
                [["InvalidPasswordLengthException","Eloquent\/Otis\/Hotp\/Exception\/InvalidPasswordLengthException.html"," < Exception",
                [        ]]        ]],["HotpGenerator","Eloquent\/Otis\/Hotp\/HotpGenerator.html","",
                [        ]],["HotpGeneratorInterface","Eloquent\/Otis\/Hotp\/HotpGeneratorInterface.html","",
                [        ]],["HotpValidator","Eloquent\/Otis\/Hotp\/HotpValidator.html","",
                [        ]],["HotpValidatorInterface","Eloquent\/Otis\/Hotp\/HotpValidatorInterface.html","",
                [        ]],["HotpValue","Eloquent\/Otis\/Hotp\/HotpValue.html","",
                [        ]]        ]],["QrCode","Eloquent\/Otis\/QrCode.html","",
                [["ErrorCorrectionLevel","Eloquent\/Otis\/QrCode\/ErrorCorrectionLevel.html"," < Multiton",
                [        ]],["GoogleChartsQrCodeUriFactory","Eloquent\/Otis\/QrCode\/GoogleChartsQrCodeUriFactory.html","",
                [        ]],["KaywaQrCodeUriFactory","Eloquent\/Otis\/QrCode\/KaywaQrCodeUriFactory.html","",
                [        ]],["QrCodeUriFactoryInterface","Eloquent\/Otis\/QrCode\/QrCodeUriFactoryInterface.html","",
                [        ]],["QrServerQrCodeUriFactory","Eloquent\/Otis\/QrCode\/QrServerQrCodeUriFactory.html","",
                [        ]]        ]],["Totp","Eloquent\/Otis\/Totp.html","",
                [["TotpGenerator","Eloquent\/Otis\/Totp\/TotpGenerator.html","",
                [        ]],["TotpGeneratorInterface","Eloquent\/Otis\/Totp\/TotpGeneratorInterface.html","",
                [        ]],["TotpValidator","Eloquent\/Otis\/Totp\/TotpValidator.html","",
                [        ]],["TotpValidatorInterface","Eloquent\/Otis\/Totp\/TotpValidatorInterface.html","",
                [        ]]        ]]        ]]        ]]        ]

